sudo: required
services:
  - docker

before_install:
  - docker build -t serhatkayaa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true serhatkaya

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-566740074909"
  bucket_path: "docker-react"   
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY