language: generic
sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - docker build -t serhatkayaa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true serhatkayaa/docker-react

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-566740074909"
  bucket_path: "docker"   
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY